services:
  keycloak:
    container_name: project2023TMA
    image: quay.io/project2023TMA/project2023TMA:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"
